sudo: required
dist: trusty
addons:
  postgresql: 10
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - postgresql-10
      - postgresql-client-10
language: ruby
cache:
  bundler: true
  yarn: true
rvm:
 - 2.5.1
node_js:
  - "8"
services:
  - redis-server
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -O /tmp/chromedriver.zip
  - unzip /tmp/chromedriver.zip -d /tmp
  - chmod 777 /tmp/chromedriver
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
env:
  global:
  - PGPORT=5433
  - CHROME_HEADLESS=true CHROME_DRIVER_PATH=/tmp/chromedriver
  - COVERAGE=true
  - CC_TEST_REPORTER_ID=f6b1339bb213fe28767691f926eec31145b3849cac8ef209c838f5de1b940c68
  - DISABLE_SPRING=true
before_script:
  - psql -c 'create database react_crud_test;' -U travis
  - yarn
  - RAILS_ENV=test NODE_ENV=test bundle exec rails webpacker:compile
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bin/yarn test
  - bin/rails test
  - bin/rails test:system
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT